package globalClasses;

public enum States {
	DISCONNECT, PLAY, PROGRESS, POSITION, COMPUTER, COFFIE_MAKER, SOFA, POOL_TABLE, SABOTAGE_INTERRUPTED, NIHGT_STARTED, GAME_ENDED, INITIAL_CONNECT, UPDATE_LOBBY;
}